apiVersion: v2

name: supaglue

description: Supaglue

home: https://supaglue.com/

keywords:
  - integration
  - crm
  - api

maintainers:
  - name: Supaglue, Inc.
    url: https://supaglue.com/

sources:
  - https://github.com/supaglue-labs/supaglue

dependencies:
  - name: postgresql
    version: '12.2.2'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: temporal
    version: '0.20.0'
    repository: file://charts/temporal
    condition: temporal.enabled
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.5

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.5.0
